"""gateway_client: small SDK for apps generated by the experiment factory.

Reuses the provider YAML and the same TokenManager (token refresh, retry, 401)
as the agent itself - generated apps never reimplement HTTP or authentication:

    from wotan.gateway_client import chat, chat_with_document, extract_json

    answer = chat("Summarize this contract", model="default")
    entities = extract_json(text, schema={...})

Also available as an equivalent JS/TS helper for frontends
(frontend/src/gateway/gatewayClient.ts) that call a local backend.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..config import AppConfig, load_config
from ..providers.base import Attachment, Message, ToolSpec
from ..providers.registry import ProviderRegistry

_config: AppConfig | None = None
_registry: ProviderRegistry | None = None


def init(config_path: str | Path | None = None, workspace: str | Path | None = None) -> None:
    """Load configuration explicitly (optional - lazily loaded otherwise)."""
    global _config, _registry
    _config = load_config(Path(config_path) if config_path else None, Path(workspace) if workspace else None)
    _registry = ProviderRegistry(_config, Path(workspace) if workspace else None)


def _ensure() -> tuple[AppConfig, ProviderRegistry]:
    global _config, _registry
    if _config is None or _registry is None:
        _config = load_config()
        _registry = ProviderRegistry(_config)
    return _config, _registry


def list_models() -> list[dict[str, Any]]:
    """Configured models (plus provider-declared metadata)."""
    cfg, _ = _ensure()
    return [
        {"provider": p.id, "model": m.id, "name": m.name or m.id, "context_window": m.context_window,
         "tools": m.tools, "streaming": m.streaming, "multimodal": m.multimodal, "weak": m.weak}
        for p, m in cfg.all_models()
    ]


async def list_models_remote(model_ref: str = "") -> list[dict[str, Any]]:
    """Query the gateway's model-listing endpoint when configured."""
    _, reg = _ensure()
    provider, _ = reg.resolve(model_ref)
    models = await provider.list_models()
    return [{"id": m.id, "name": m.name or m.id} for m in models]


async def chat(
    prompt: str,
    *,
    system: str = "",
    model: str = "",
    temperature: float = 0.2,
    max_tokens: int | None = None,
    history: list[dict[str, Any]] | None = None,
) -> str:
    """One chat turn; returns the assistant text."""
    cfg, reg = _ensure()
    provider, model_id = reg.resolve(model or cfg.default_model)
    messages: list[Message] = []
    if system:
        messages.append(Message(role="system", content=system))
    for m in history or []:
        messages.append(Message(role=m.get("role", "user"), content=m.get("content", "")))
    messages.append(Message(role="user", content=prompt))
    result = await provider.chat(messages, model=model_id, temperature=temperature, max_tokens=max_tokens)
    return result.text


async def chat_with_image(
    prompt: str,
    image_path: str | Path,
    *,
    system: str = "",
    model: str = "",
    temperature: float = 0.2,
) -> str:
    """Chat with an image attachment (inline base64 / upload per the YAML)."""
    import base64

    cfg, reg = _ensure()
    provider, model_id = reg.resolve(model or cfg.default_model)
    p = Path(image_path)
    data = base64.b64encode(p.read_bytes()).decode("ascii")
    mime = _guess_mime(p)
    att = Attachment(kind="image", mime=mime, data_b64=data, name=p.name, path=str(p))
    messages = []
    if system:
        messages.append(Message(role="system", content=system))
    messages.append(Message(role="user", content=prompt, attachments=[att]))
    result = await provider.chat(messages, model=model_id, temperature=temperature)
    return result.text


async def chat_with_document(
    prompt: str,
    document_path: str | Path,
    *,
    system: str = "",
    model: str = "",
    temperature: float = 0.2,
    extract_text_first: bool = True,
) -> str:
    """Chat with a document (PDF...). PDFs are text-extracted locally first when
    possible; pages-as-images is used when the model accepts images and text
    extraction fails (multimodal config in the YAML)."""
    cfg, reg = _ensure()
    provider, model_id = reg.resolve(model or cfg.default_model)
    p = Path(document_path)
    text_content = ""
    if extract_text_first and p.suffix.lower() == ".pdf":
        try:
            from pypdf import PdfReader

            reader = PdfReader(str(p))
            text_content = "\n".join((page.extract_text() or "") for page in reader.pages)
        except Exception:
            text_content = ""
    if text_content.strip():
        messages = []
        if system:
            messages.append(Message(role="system", content=system))
        messages.append(
            Message(role="user", content=f"{prompt}\n\n<untrusted-data source=\"document:{p.name}\">\n{text_content[:20000]}\n</untrusted-data>")
        )
        result = await provider.chat(messages, model=model_id, temperature=temperature)
        return result.text
    import base64

    data = base64.b64encode(p.read_bytes()).decode("ascii")
    att = Attachment(kind="document", mime=_guess_mime(p), data_b64=data, name=p.name, path=str(p))
    messages = []
    if system:
        messages.append(Message(role="system", content=system))
    messages.append(Message(role="user", content=prompt, attachments=[att]))
    result = await provider.chat(messages, model=model_id, temperature=temperature)
    return result.text


async def extract_json(
    text: str,
    *,
    schema: dict[str, Any] | None = None,
    model: str = "",
    max_repairs: int = 2,
) -> Any:
    """Structured output: ask for JSON matching a schema, validate, repair."""
    cfg, reg = _ensure()
    provider, model_id = reg.resolve(model or cfg.default_model)
    schema_txt = json.dumps(schema, ensure_ascii=False) if schema else "{}"
    prompt = (
        "Extract structured data from the text below. Respond with ONLY JSON matching this JSON Schema "
        f"(no markdown fences, no commentary):\n{schema_txt}\n\n"
        f"TEXT:\n{text[:12000]}"
    )
    out = await provider.chat([Message(role="user", content=prompt)], model=model_id, temperature=0.0)
    raw = out.text.strip()
    for _ in range(max_repairs + 1):
        try:
            obj = json.loads(raw)
            _validate_schema(obj, schema or {})
            return obj
        except (json.JSONDecodeError, ValueError) as exc:
            repair = (
                f"The previous answer was invalid ({exc}). Return ONLY corrected JSON for this schema:\n{schema_txt}\n\n"
                f"PREVIOUS ANSWER:\n{raw[:4000]}"
            )
            out = await provider.chat([Message(role="user", content=repair)], model=model_id, temperature=0.0)
            raw = out.text.strip()
    raise ValueError(f"extract_json: model did not return valid JSON after {max_repairs} repairs: {raw[:200]}")


def _validate_schema(obj: Any, schema: dict[str, Any]) -> None:
    if not schema:
        return
    from ..providers.text_tools import validate_arguments

    if isinstance(obj, dict):
        issue = validate_arguments("extract_json", obj, schema)
    else:
        issue = validate_arguments("extract_json", {"value": obj}, {"type": "object", "properties": {"value": schema}})
    if issue is not None:
        raise ValueError(issue.error)


async def run_workflow(name: str, inputs: dict[str, Any], *, timeout: float = 60.0) -> Any:
    """Call a configured external workflow (low-code platform endpoint)."""
    import httpx
    from jinja2 import Template

    cfg, reg = _ensure()
    et = next((t for t in cfg.external_tools if t.name == name), None)
    if et is None:
        raise KeyError(f"unknown workflow {name!r}; configured: {[t.name for t in cfg.external_tools]}")
    tpl = Template(et.input_template)
    tpl.globals["tojson"] = lambda v: json.dumps(v, ensure_ascii=False)
    rendered = tpl.render(inputs=inputs, **inputs)
    try:
        payload = json.loads(rendered) if rendered.strip().startswith(("{", "[")) else rendered
    except json.JSONDecodeError:
        payload = rendered
    pc = cfg.find_provider(et.provider_id) if et.provider_id else None
    base = (pc.base_url if pc else "").rstrip("/")
    url = et.endpoint if et.endpoint.startswith("http") else f"{base}/{et.endpoint.lstrip('/')}"
    headers = dict(et.headers)
    if pc is not None:
        prov = reg.get(pc.id)
        tokens = getattr(prov, "tokens", None)
        if tokens is not None:
            await tokens.apply_auth(headers)
    async with httpx.AsyncClient(timeout=timeout or et.timeout_seconds) as client:
        resp = await client.request(et.method, url, json=payload if isinstance(payload, (dict, list)) else None,
                                    content=None if isinstance(payload, (dict, list)) else str(payload), headers=headers)
        if resp.status_code >= 400:
            raise RuntimeError(f"workflow {name!r} returned HTTP {resp.status_code}: {resp.text[:300]}")
        data = resp.json()
    from ..providers.generic_http import extract_path

    return extract_path(data, et.result_path) if et.result_path not in ("", "$") else data


def _guess_mime(p: Path) -> str:
    import mimetypes

    mime, _ = mimetypes.guess_type(str(p))
    return mime or "application/octet-stream"


async def aclose() -> None:
    global _config, _registry
    if _registry is not None:
        await _registry.aclose()
    _config = None
    _registry = None
